### ISSUE TITLE
Server is not running due to typo in settings.py file

### ISSUE THREAD

**Issue by DeanCivlin** [redhat-beyond/AcadeMe#37]

**Comment by DeanCivlin** [comment]
First, we saw that `vagrant up` not running the server. than we tried to run the runserver command manually and saw that we are getting this error:

`raise ImportError(msg)
ImportError: Module 'AcadeMeData.apps' does not contain a 'AcadeMeDataConfig' class. Choices are: 'AcademedataConfig'.`

So we understood the issue and fixed it.

[PR link for the fix](https://github.com/redhat-beyond/AcadeMe/pull/36)

**Comment by razashtar93** [comment]
PR #36  has been merged.

Done.
