### ISSUE TITLE
Create models.py file and add class Users, relevant migrations file and test class

### ISSUE THREAD

**Issue by razashtar93** [redhat-beyond/AcadeMe#39]
In the file models.py:
  add the class "Users", and add relevant fields and relevant methods.

In migrations directory:
  create file "0002_users_test_data", and add test data. (see page 41; Task 5: Adding test data; in ToolIntroductionGit.pdf)

In the file tests.py:
  add the class "TestUsers", and add relevant test methods. (see page 18 in Automated Software Test (B6).pdf for example)

**Comment by DanWaldman** [comment]
#49

**Comment by razashtar93** [comment]
#59
Done. Closing.
