### ISSUE TITLE
Add: class "MessageBoards", relevant migrations file and test class

### ISSUE THREAD

**Issue by razashtar93** [redhat-beyond/AcadeMe#40]
In the file models.py:
  add the class "MessageBoards", and add relevant fields and relevant methods.

In migrations directory:
  create file "0003_messageBoards_test_data", and add test data. (see page 41; Task 5: Adding test data; in ToolIntroductionGit.pdf)

In the file tests.py
  add the class "TestMessageBoards", and add relevant test methods. (see page 18 in Automated Software Test (B6).pdf for example)

**Comment by DanWaldman** [comment]
Resolved #65 #64
