### ISSUE TITLE
Add: class "Messages", relevant migrations file and test class

### ISSUE THREAD

**Issue by razashtar93** [redhat-beyond/AcadeMe#41]
In the file models.py:
add the class "Messages", and add relevant fields and relevant methods.

In migrations directory:
create file "0004_messages_test_data", and add test data. (see page 41; Task 5: Adding test data; in ToolIntroductionGit.pdf)

In the file tests.py:
add the class "TestMessages", and add relevant test methods. (see page 18 in Automated Software Test (B6).pdf for example)

**Comment by shakedhagag** [comment]
Divided this issue into to 2
