### ISSUE TITLE
Add: class "Degree", relevant migrations file and test class

### ISSUE THREAD

**Issue by razashtar93** [redhat-beyond/AcadeMe#46]
In the file models.py:
add the class "Degree", and add relevant fields and relevant methods.

In migrations directory:
create file "0007_Degree_test_data", and add test data. (see page 41; Task 5: Adding test data; in ToolIntroductionGit.pdf)

In the file tests.py:
add the class "TestDegree", and add relevant test methods. (see page 18 in Automated Software Test (B6).pdf for example)

**Comment by DanielItkes** [comment]
Waiting for approval.
#52 #53

**Comment by razashtar93** [comment]
Done. closing …
