### ISSUE TITLE
Add: class "Course", relevant migrations file and test class

### ISSUE THREAD

**Issue by razashtar93** [redhat-beyond/AcadeMe#48]
In the file models.py:
add the class "Course", and add relevant fields and relevant methods.

In migrations directory:
create file "0009_Course_test_data", and add test data. (see page 41; Task 5: Adding test data; in ToolIntroductionGit.pdf)

In the file tests.py:
add the class "TestCourse", and add relevant test methods. (see page 18 in Automated Software Test (B6).pdf for example)

**Comment by DanielItkes** [comment]
Code is done, waiting for PR #52 to be merged and I'll send a PR.

**Comment by DanielItkes** [comment]
#60
