### ISSUE TITLE
Remove the user module 'type' property

### ISSUE THREAD

**Issue by DanWaldman** [redhat-beyond/AcadeMe#77]
After a team discussion - it was agreed to remove 'type' property from user.
This was decided after we came to the agreement that a user may be a student for a certain course, and an expert for another, and therefore a field defining if a user is an expert or student would be wrong.

**Comment by Omeramsc** [comment]
Please follow the contributing guidelines (although still a WIP PR) when posting an issue. 
besides the title, It has 0 context about why this change is needed or what is the acceptance critiria.
