### ISSUE TITLE
Implement Homepage UI and Logic

### ISSUE THREAD

**Issue by DeanCivlin** [redhat-beyond/AcadeMe#93]
@razashtar93 and I will implement the new home page.

* We will add homepage.html and app_layout.html files
* We will also add two CSS files incoherence to the HTML files
* We will add a new transparent logo for the home page
* We will update the views.py and urls.py files to match the changes we will make

**Comment by Omeramsc** [comment]
Please follow the guidelines for informative issues.

**Comment by DeanCivlin** [comment]
@Omeramsc As Requested I added issue description so it will be much informative.
